### ISSUE TITLE
Automated building

### ISSUE THREAD

**Issue by stunbrick** [BrothersChimes/EvoSumo#2]

**Comment by mark-chimes** [comment]
Done. It's a very simple .yaml file. All the hard work will be done in the make file.

**Comment by stunbrick** [comment]
Automated Building has been re-opened, sorry @mark-chimes, its not working yet! We'll get there though, just hang in there!

https://images-na.ssl-images-amazon.com/images/I/91HiqSzRYwL._SY450_.jpg

**Comment by mark-chimes** [comment]
Dunno what you're talking about... :-P
